# Generated by Django 5.2.14 on 2026-05-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('date', models.DateField()),
                ('buy', models.DecimalField(decimal_places=5, max_digits=12)),
                ('sell', models.DecimalField(decimal_places=5, max_digits=12)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('bccr', 'BCCR'), ('manual', 'Manual')], default='bccr', max_length=10)),
            ],
            options={
                'verbose_name': 'Tipo de cambio',
                'verbose_name_plural': 'Tipos de cambio',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['currency', '-date'], name='finance_exc_currenc_6bb913_idx')],
                'unique_together': {('currency', 'date')},
            },
        ),
    ]
