# Generated by Django 5.2.14 on 2026-05-26 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('identificacion', models.CharField(blank=True, max_length=50)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
                'constraints': [models.CheckConstraint(condition=models.Q(('nombre', ''), _negated=True), name='cliente_nombre_no_vacio')],
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('direccion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin_estimada', models.DateField(blank=True, null=True)),
                ('moneda_reporte', models.CharField(choices=[('CRC', 'Colones'), ('USD', 'Dólares')], default='USD', max_length=3)),
                ('estado', models.CharField(choices=[('planificada', 'Planificada'), ('en_curso', 'En curso'), ('pausada', 'Pausada'), ('finalizada', 'Finalizada')], default='planificada', max_length=20)),
                ('next_oc_seq', models.PositiveIntegerField(default=1)),
                ('notas', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obras', to='core.cliente')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'ordering': ['-fecha_inicio', 'nombre'],
            },
        ),
    ]
