# Generated by Django 5.2.14 on 2026-05-26 06:37

import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='core.obra')),
            ],
            options={
                'verbose_name': 'Categoría de presupuesto',
                'verbose_name_plural': 'Categorías de presupuesto',
                'ordering': ['obra', 'orden', 'nombre'],
                'unique_together': {('obra', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monto_currency', djmoney.models.fields.CurrencyField(choices=[('CRC', 'Colones (₡)'), ('USD', 'Dólares ($)')], default='CRC', editable=False, max_length=3)),
                ('monto', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('notas', models.TextField(blank=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriapresupuesto')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='core.obra')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'unique_together': {('obra', 'categoria')},
            },
        ),
    ]
