import pytest

pytestmark = pytest.mark.django_db


def test_proveedor_factory():
    from apps.catalogo.tests.factories import ProveedorFactory
    p = ProveedorFactory()
    assert p.pk is not None
    assert p.activo is True


def test_item_catalogo_factory():
    from apps.catalogo.tests.factories import ItemCatalogoFactory
    item = ItemCatalogoFactory()
    assert item.pk is not None
    assert item.tipo == "material"
    assert item.estado == "aprobado"
    assert item.slug != ""  # debe haber autogenerated slug
