# Generated by Django 5.2.14 on 2026-05-26 08:17

import apps.facturas.models
import django.db.models.deletion
import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0007_grant_pago_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('xml', 'XML'), ('pdf', 'PDF'), ('imagen', 'Imagen')], max_length=10)),
                ('tipo_comprobante', models.CharField(blank=True, choices=[('FE', 'Factura Electrónica'), ('TE', 'Tiquete Electrónico'), ('NC', 'Nota de Crédito'), ('ND', 'Nota de Débito'), ('FEC', 'Factura Electrónica de Compra'), ('FEE', 'Factura Electrónica de Exportación')], max_length=5)),
                ('archivo_original', models.FileField(upload_to=apps.facturas.models.factura_upload_path)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('extracted', 'Extraída'), ('confirmed', 'Confirmada'), ('error', 'Error')], default='pending', max_length=20)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('clave_numerica', models.CharField(blank=True, db_index=True, help_text='Alfanumérica en v4.4 (no integer).', max_length=50)),
                ('numero_consecutivo', models.CharField(blank=True, max_length=80)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('monto_total_currency', djmoney.models.fields.CurrencyField(choices=[('CRC', 'Colones (₡)'), ('USD', 'Dólares ($)')], default='CRC', editable=False, max_length=3, null=True)),
                ('monto_total', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('condicion_venta', models.CharField(blank=True, max_length=2)),
                ('medios_pago', models.JSONField(blank=True, default=list)),
                ('fx_rate_applied', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('fx_rate_date', models.DateField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('confirmada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('oc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='compras.ordencompra')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-created_at'],
                'permissions': [('confirm_factura', 'Puede confirmar una Factura extraída')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('clave_numerica', ''), _negated=True), fields=('clave_numerica',), name='factura_clave_unique')],
            },
        ),
    ]
