# Generated by Django 5.2.14 on 2026-05-26 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_bodega'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('identificacion', models.CharField(blank=True, max_length=20)),
                ('email_facturacion', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ItemCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('material', 'Material'), ('servicio', 'Servicio')], max_length=10)),
                ('nombre_canonico', models.CharField(max_length=200)),
                ('unidad', models.CharField(choices=[('saco', 'Saco'), ('kg', 'Kg'), ('m3', 'm³'), ('m2', 'm²'), ('m', 'm'), ('unidad', 'Unidad'), ('varilla', 'Varilla'), ('galon', 'Galón'), ('litro', 'Litro'), ('hora', 'Hora'), ('dia', 'Día'), ('visita', 'Visita'), ('global', 'Global'), ('mes', 'Mes')], max_length=20)),
                ('slug', models.SlugField(max_length=220)),
                ('alias', models.TextField(blank=True, help_text='Strings alternativos para autocomplete, uno por línea')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('aprobado', 'Aprobado'), ('inactivo', 'Inactivo')], default='aprobado', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('categoria_sugerida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_sugeridos', to='core.categoriapresupuesto')),
                ('sugerido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_catalogo_sugeridos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item del catálogo',
                'verbose_name_plural': 'Items del catálogo',
                'ordering': ['nombre_canonico'],
                'indexes': [models.Index(fields=['estado'], name='catalogo_it_estado_bfc7e2_idx'), models.Index(fields=['tipo'], name='catalogo_it_tipo_9c30ca_idx'), models.Index(fields=['slug'], name='catalogo_it_slug_af1bb7_idx')],
            },
        ),
    ]
