# Generated by Django 5.2.14 on 2026-05-26 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcatalogo',
            options={'ordering': ['nombre_canonico'], 'permissions': [('suggest_item', 'Puede sugerir items al catálogo'), ('approve_item', 'Puede aprobar/fusionar items del catálogo')], 'verbose_name': 'Item del catálogo', 'verbose_name_plural': 'Items del catálogo'},
        ),
    ]
