# Generated by Django 5.2.14 on 2026-05-26 07:17

import apps.compras.models
import django.db.models.deletion
import djmoney.models.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_alter_itemcatalogo_options'),
        ('core', '0004_create_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_cotizacion', models.CharField(max_length=80)),
                ('fecha', models.DateField()),
                ('fecha_validez', models.DateField(blank=True, null=True)),
                ('moneda', models.CharField(choices=[('CRC', 'Colones'), ('USD', 'Dólares')], default='CRC', max_length=3)),
                ('subtotal_currency', djmoney.models.fields.CurrencyField(choices=[('CRC', 'Colones (₡)'), ('USD', 'Dólares ($)')], default='CRC', editable=False, max_length=3)),
                ('subtotal', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('iva_currency', djmoney.models.fields.CurrencyField(choices=[('CRC', 'Colones (₡)'), ('USD', 'Dólares ($)')], default='CRC', editable=False, max_length=3)),
                ('iva', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('total_currency', djmoney.models.fields.CurrencyField(choices=[('CRC', 'Colones (₡)'), ('USD', 'Dólares ($)')], default='CRC', editable=False, max_length=3)),
                ('total', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('condiciones_pago', models.CharField(blank=True, max_length=200)),
                ('plazo_entrega_dias', models.PositiveIntegerField(blank=True, null=True)),
                ('pct_anticipo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to=apps.compras.models.cotizacion_upload_path)),
                ('es_especial', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('recibida', 'Recibida'), ('en_revision', 'En revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('vencida', 'Vencida')], default='recibida', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='core.obra')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.proveedor')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha', '-pk'],
                'permissions': [('approve_cotizacion', 'Puede aprobar Cotizacion → crear OrdenCompra')],
            },
        ),
        migrations.CreateModel(
            name='CotizacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unidad', models.CharField(max_length=20)),
                ('precio_unitario', models.DecimalField(decimal_places=5, max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('iva_monto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('codigo_cabys', models.CharField(blank=True, max_length=13)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.cotizacion')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.itemcatalogo')),
            ],
            options={
                'verbose_name': 'Item de cotización',
                'verbose_name_plural': 'Items de cotización',
                'ordering': ['cotizacion', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField()),
                ('fecha_requerida', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], default='abierta', max_length=20)),
                ('es_especial', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.categoriapresupuesto')),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfqs_creadas', to=settings.AUTH_USER_MODEL)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfqs', to='core.obra')),
            ],
            options={
                'verbose_name': 'Solicitud de cotización',
                'verbose_name_plural': 'Solicitudes de cotización',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='rfq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='compras.solicitudcotizacion'),
        ),
    ]
