"""Asigna permisos de apps.compras a los grupos existentes."""
# Generated by Django 5.2 + Task 3.4

from django.db import migrations


def grant_permissions(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    # Crear los permissions de la app si no existen (post_migrate puede no haber corrido)
    from django.contrib.auth.management import create_permissions
    from django.apps import apps as django_apps
    for app_config in django_apps.get_app_configs():
        if app_config.name == "apps.compras":
            create_permissions(app_config, verbosity=0)

    try:
        supervisor = Group.objects.get(name="supervisor")
        operativo = Group.objects.get(name="operativo")
        lector = Group.objects.get(name="lector")
    except Group.DoesNotExist:
        return  # grupos no existen aún (migración inicial sin Task 1.5)

    cts = ContentType.objects.filter(app_label="compras")
    for ct in cts:
        # supervisor: TODO
        for p in Permission.objects.filter(content_type=ct):
            supervisor.permissions.add(p)
        # operativo + lector: view
        view = Permission.objects.filter(content_type=ct, codename__startswith="view_").first()
        if view:
            operativo.permissions.add(view)
            lector.permissions.add(view)

    # operativo también puede add/change SolicitudCotizacion + Cotizacion
    for model in ("solicitudcotizacion", "cotizacion"):
        try:
            ct = ContentType.objects.get(app_label="compras", model=model)
            for codename in (f"add_{model}", f"change_{model}"):
                p = Permission.objects.filter(content_type=ct, codename=codename).first()
                if p:
                    operativo.permissions.add(p)
        except ContentType.DoesNotExist:
            pass


def rollback(apps, schema_editor):
    """Idempotente — borrar permisos requeriría tracking. No-op acceptable."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("compras", "0001_initial"),
        ("core", "0004_create_groups"),
    ]
    operations = [
        migrations.RunPython(grant_permissions, rollback),
    ]
