# Generated by Django 5.2.14 on 2026-05-26 07:31

import django.db.models.deletion
import djmoney.models.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_itemcatalogo_options'),
        ('compras', '0002_grant_groups_permissions'),
        ('core', '0004_create_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_oc', models.CharField(help_text='Formato: <SLUG_OBRA>-OC-NNNN. Generado por compras.services.generate_numero_oc.', max_length=80, unique=True)),
                ('fecha_aprobacion', models.DateField()),
                ('moneda', models.CharField(choices=[('CRC', 'Colones'), ('USD', 'Dólares')], default='CRC', max_length=3)),
                ('monto_total_currency', djmoney.models.fields.CurrencyField(choices=[('CRC', 'Colones (₡)'), ('USD', 'Dólares ($)')], default='CRC', editable=False, max_length=3)),
                ('monto_total', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('fx_rate_applied', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('fx_rate_date', models.DateField(blank=True, null=True)),
                ('es_especial', models.BooleanField(default=False)),
                ('tiempo_estimado_dias', models.PositiveIntegerField(blank=True, null=True)),
                ('pct_anticipo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('estado', models.CharField(choices=[('autorizada', 'Autorizada'), ('pagada_parcial', 'Pagada parcial'), ('pagada', 'Pagada'), ('entregada_parcial', 'Entregada parcial'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='autorizada', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('aprobada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ocs_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.categoriapresupuesto')),
                ('cotizacion_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocs', to='compras.cotizacion')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='core.obra')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.proveedor')),
            ],
            options={
                'verbose_name': 'Orden de compra',
                'verbose_name_plural': 'Órdenes de compra',
                'ordering': ['-fecha_aprobacion', '-pk'],
                'permissions': [('cancel_oc', 'Puede cancelar/anular una OrdenCompra autorizada')],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_nombre_snapshot', models.CharField(blank=True, max_length=200)),
                ('material_unidad_snapshot', models.CharField(blank=True, max_length=20)),
                ('descripcion', models.CharField(max_length=300)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unidad', models.CharField(max_length=20)),
                ('precio_unitario', models.DecimalField(decimal_places=5, max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('iva_monto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('codigo_cabys', models.CharField(blank=True, max_length=13)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.itemcatalogo')),
                ('oc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.ordencompra')),
            ],
            options={
                'verbose_name': 'Item de OC',
                'verbose_name_plural': 'Items de OC',
                'ordering': ['oc', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Hito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('fecha_estimada', models.DateField(blank=True, null=True)),
                ('completado', models.BooleanField(default=False)),
                ('fecha_completado', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('oc_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitos', to='compras.ordencompraitem')),
            ],
            options={
                'verbose_name': 'Hito',
                'verbose_name_plural': 'Hitos',
                'ordering': ['oc_item', 'orden'],
            },
        ),
    ]
