# Generated by Django 5.2.14 on 2026-05-26 07:51

import apps.compras.models
import django.db.models.deletion
import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_grant_approve_cotizacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_programada', models.DateField()),
                ('fecha_realizada', models.DateField(blank=True, null=True)),
                ('monto_currency', djmoney.models.fields.CurrencyField(choices=[('CRC', 'Colones (₡)'), ('USD', 'Dólares ($)')], default='CRC', editable=False, max_length=3)),
                ('monto', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('metodo', models.CharField(choices=[('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('otro', 'Otro')], max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to=apps.compras.models.pago_upload_path)),
                ('fx_rate_applied', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('fx_rate_date', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('hitos_relacionados', models.ManyToManyField(blank=True, related_name='pagos', to='compras.hito')),
                ('marcado_pagado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_marcados', to=settings.AUTH_USER_MODEL)),
                ('oc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='compras.ordencompra')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_programada'],
                'permissions': [('mark_paid', 'Puede marcar Pago como realizado')],
            },
        ),
    ]
