"""Asigna permisos de Pago a los grupos."""
# Generated by Django 5.2.14 on 2026-05-26 07:51

from django.db import migrations


def grant(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    # Crear permissions si no existen
    from django.contrib.auth.management import create_permissions
    from django.apps import apps as django_apps
    for app_config in django_apps.get_app_configs():
        if app_config.name == "apps.compras":
            create_permissions(app_config, verbosity=0)

    try:
        supervisor = Group.objects.get(name="supervisor")
        operativo = Group.objects.get(name="operativo")
        lector = Group.objects.get(name="lector")
    except Group.DoesNotExist:
        return

    try:
        ct = ContentType.objects.get(app_label="compras", model="pago")
    except ContentType.DoesNotExist:
        return

    # supervisor: TODO incluyendo mark_paid
    for p in Permission.objects.filter(content_type=ct):
        supervisor.permissions.add(p)

    # operativo: view + add + change Pago (puede programar pero NO mark_paid)
    for codename in ("view_pago", "add_pago", "change_pago"):
        p = Permission.objects.filter(content_type=ct, codename=codename).first()
        if p:
            operativo.permissions.add(p)

    # lector: solo view
    view = Permission.objects.filter(content_type=ct, codename="view_pago").first()
    if view:
        lector.permissions.add(view)


def rollback(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("compras", "0006_pago"),
    ]
    operations = [
        migrations.RunPython(grant, rollback),
    ]
