# Generated by Django 5.2.14 on 2026-05-26 08:38

import apps.entregas.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_alter_itemcatalogo_options'),
        ('compras', '0007_grant_pago_permissions'),
        ('core', '0004_create_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('recibido_por', models.CharField(help_text='Texto libre — nombre de quien recibió en obra.', max_length=120)),
                ('completa', models.BooleanField(default=False, help_text='Marcar True si esta entrega cierra la OC.')),
                ('notas', models.TextField(blank=True)),
                ('bodega_destino', models.ForeignKey(blank=True, help_text='Bodega donde se almacenó. Nullable en MVP (obligatorio cuando llegue módulo inventario en roadmap).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas', to='core.bodega')),
                ('oc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='compras.ordencompra')),
                ('registrada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'ordering': ['-fecha', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='EntregaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(upload_to=apps.entregas.models.entrega_foto_upload_path)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='entregas.entrega')),
                ('subida_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entrega_fotos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foto de entrega',
                'verbose_name_plural': 'Fotos de entrega',
                'ordering': ['entrega', '-fecha'],
            },
        ),
        migrations.CreateModel(
            name='EntregaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unidad', models.CharField(max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='entregas.entrega')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.itemcatalogo')),
                ('oc_item', models.ForeignKey(blank=True, help_text='Link al item de la OC para reconciliación. Nullable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_items', to='compras.ordencompraitem')),
            ],
            options={
                'verbose_name': 'Item de entrega',
                'verbose_name_plural': 'Items de entrega',
                'ordering': ['entrega', 'pk'],
            },
        ),
    ]
